PIECES = {
    'WHITE_KING': 'WK',
    'BLACK_KING': 'BK',
    'WHITE_QUEEN': 'WQ',
    'BLACK_QUEEN': 'BQ',
    'WHITE_ROOK': 'WR',
    'BLACK_ROOK': 'BR',
    'WHITE_KNIGHT': 'WN',
    'BLACK_KNIGHT': 'BN',
    'WHITE_BISHOP': 'WB',
    'BLACK_BISHOP': 'BB',
    'WHITE_PAWN': 'WP',
    'BLACK_PAWN': 'BP',
    'EMPTY_TILE': 'ET',
}

MAPPING = {
    'WK': 1,
    'WQ': 2,
    'WB': 3,
    'WN': 4,
    'WR': 5,
    'WP': 6,
    'BK': 7,
    'BQ': 8,
    'BB': 9,
    'BN': 10,
    'BR': 11,
    'BP': 12,
    'ET': -1,
}

SCORES = {
    'WK': 100,
    'WQ': 9,
    'WB': 3,
    'WN': 3,
    'WR': 5,
    'WP': 1,
    'BK': -100,
    'BQ': -9,
    'BB': -3,
    'BN': -3,
    'BR': -5,
    'BP': -1,
    'ET': 0,
}
